baseURL = "https://tomkonidas.com/"
languageCode = "en-us"
title = "Tom Konidas"
theme = "entropy"
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

[markup]
  [markup.highlight]
    theme = 'dracula'

[author]
  name = "Tom Konidas"
  email = "tomkonidas@pm.me"
  biography = "some bio"
  [[author.socials]]
    name = "Twitter"
    url = "https://twitter.com/tomkonidas"
  [[author.socials]]
    name = "GitHub"
    url = "https://github.com/tomkonidas"
  [[author.socials]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/tomkonidas/"
  [[author.socials]]
    name = "SoundCloud"
    url = "https://soundcloud.com/tomkonidas"
  [author.location]
    city = "Montr√©al"
    region = "CA-QC"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 1
  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 2

[params]
  description = "some description"
  color = "#533FEB"
